### PR TITLE
hide plus button when the user can't create new survey with the selec…

### PR DESCRIPTION
**Pull request by idelcano**
…ted filter
Closes https://github.com/EyeSeeTea/malariapp/issues/1752

### CODE REVIEW

**Review by xurxodev — CHANGES_REQUESTED** [review]
@idelcano I do not understand why all this new code is necessary (new db queries, etc.) because currently the surveys in progress are being filtered by org unit and program in the list, so I think that if this current filter returns data, then hide the button of a new survey, but a new survey button should be displayed, can you review it, please?

**Comment by idelcano** [comment]
@xurxodev i talked with @ifoche  and i follow your interpretation but checking if the orgunit/program  combination is valid.

**Comment by xurxodev** [comment]
Ok @idelcano but between my comment and your comment there is not any commit, have you forgotten to push changes?

**Comment by idelcano** [comment]
@xurxodev  yes sorry, i pushed in command-line but the push failed and i didn't see the error.

**Review by xurxodev — APPROVED** [review]
thanks @idelcano

**Pull request merged**
