### PR TITLE
Feature composite score domain

### LINKED ISSUE #1980: Create CompositeScore domain entity and repository to retrieve from DB
Create domain entity with best practices and add all necessary code only for being used for the pull, some tips:

* Avoid public setters by default, please read this article
http://xurxodev.com/clean-architecture-code-smells-parte-2/
* create a constructor with mandatory fields
* add relations to other entities by uid (no object reference)
* add validations to mandatory info when a new instance is created
* create unit tests
* create the repository for retrieve CompositeScores by program uid

### PR DESCRIPTION
**Pull request by manuelplazaspalacio**
Close #1980

### CODE REVIEW

**Review by xurxodev — CHANGES_REQUESTED** [review]
@manuelplazaspalacio There is several problems on this PR:
- There is unit test failing on CompositeScoreShould
- The relation between parent and child is not aggregate root with an aggregate root that It's when has sense relation by uid. Here this relation should be between domain entities because load a children without parent has no sense.
- After merge with development, method requiredNotEmpty in RequiredChecker is unnecesary because required has isempty validation

**Review by xurxodev — CHANGES_REQUESTED** [review]
@manuelplazaspalacio there is a crash retrieving composite score from the database. I have add this code in some part of the app to test:
        CompositeScoreDataSource dataSource = new CompositeScoreDataSource();
        List<CompositeScore> compositeScores = dataSource.getCompositesScoreByProgram("Wps8E2P8P9S");

Crash:
    Process: org.eyeseetea.malariacare.questmark_dev, PID: 27557
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.eyeseetea.malariacare.questmark_dev/org.eyeseetea.malariacare.DashboardActivity}: java.lang.IllegalArgumentException: ParentUid is required and not empty
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.IllegalArgumentException: ParentUid is required and not empty
        at org.eyeseetea.malariacare.domain.utils.RequiredChecker.required(RequiredChecker.java:13)
        at org.eyeseetea.malariacare.domain.entity.CompositeScore.addParent(CompositeScore.java:50)
        at org.eyeseetea.malariacare.data.database.datasources.CompositeScoreDataSource.convertFromDBToDomain(CompositeScoreDataSource.java:44)
        at org.eyeseetea.malariacare.data.database.datasources.CompositeScoreDataSource.convertCompositeScoreChildren(CompositeScoreDataSource.java:24)
        at org.eyeseetea.malariacare.data.database.datasources.CompositeScoreDataSource.getCompositesScoreByProgram(CompositeScoreDataSource.java:18)
        at org.eyeseetea.malariacare.DashboardActivity.onCreate(DashboardActivity.java:69)
        at android.app.Activity.performCreate(Activity.java:6679)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Review by xurxodev — CHANGES_REQUESTED** [review]
@manuelplazaspalacio currently you are executing many queries to database to retrieve composite scores because realize one query for composite score childrens. The first query return all necessary root and childrens, then I think secondary queries is not necessary and we should composite the tree in memory only with one query to database

**Comment by manuelplazaspalacio** [comment]
I debug  the app doing ` List compositeScores = dataSource.getCompositesScoreByProgram("Wps8E2P8P9S"); `
And in the only place where I make a query is when I call the method `CompositeScoreDB.listByProgram(programDB);`
When I execute the method:
```
public List<CompositeScoreDB> getCompositeScoreChildren() {
        if (this.compositeScoreChildren == null){
            this.compositeScoreChildren = new Select()
                    .from(CompositeScoreDB.class)
                    .where(CompositeScoreDB_Table.id_composite_score_parent.eq(this.getId_composite_score()))
                    .orderBy(OrderBy.fromProperty(CompositeScoreDB_Table.order_pos))
                    .queryList();
        }
        return this.compositeScoreChildren;
    }
```
The compositeScoreChildren is always different than null, it's initialised in the method  `CompositeScoreDB.listByProgram(programDB);` and never do any query.

**Review by xurxodev — CHANGES_REQUESTED** [review]
@manuelplazaspalacio  I have added traces to print queries realized and this is the result:
07-03 07:18:17.813 30154-30154/org.eyeseetea.malariacare.questmark_dev D/CompositeScoreDB: Executing listByprogram: Wps8E2P8P9S
07-03 07:18:22.417 30154-30154/org.eyeseetea.malariacare.questmark_dev D/CompositeScoreDB: Executing getCompositeScoreChildren for id_composite_score: 1021
07-03 07:18:32.685 30154-30154/org.eyeseetea.malariacare.questmark_dev D/CompositeScoreDB: Executing getCompositeScoreChildren for id_composite_score: 1024
07-03 07:18:43.563 30154-30154/org.eyeseetea.malariacare.questmark_dev D/CompositeScoreDB: Executing getCompositeScoreChildren for id_composite_score: 922
07-03 07:18:57.547 30154-30154/org.eyeseetea.malariacare.questmark_dev D/CompositeScoreDB: Executing getCompositeScoreChildren for id_composite_score: 1025
07-03 07:18:57.550 30154-30154/org.eyeseetea.malariacare.questmark_dev D/CompositeScoreDB: Executing getCompositeScoreChildren for id_composite_score: 921
07-03 07:18:57.551 30154-30154/org.eyeseetea.malariacare.questmark_dev D/CompositeScoreDB: Executing getCompositeScoreChildren for id_composite_score: 920
07-03 07:18:57.552 30154-30154/org.eyeseetea.malariacare.questmark_dev D/CompositeScoreDB: Executing getCompositeScoreChildren for id_composite_score: 919
07-03 07:18:57.555 30154-30154/org.eyeseetea.malariacare.questmark_dev D/CompositeScoreDB: Executing getCompositeScoreChildren for id_composite_score: 1023
07-03 07:18:57.557 30154-30154/org.eyeseetea.malariacare.questmark_dev D/CompositeScoreDB: Executing getCompositeScoreChildren for id_composite_score: 916
07-03 07:18:57.560 30154-30154/org.eyeseetea.malariacare.questmark_dev D/CompositeScoreDB: Executing getCompositeScoreChildren for id_composite_score: 915
07-03 07:18:57.563 30154-30154/org.eyeseetea.malariacare.questmark_dev D/CompositeScoreDB: Executing getCompositeScoreChildren for id_composite_score: 1022
07-03 07:18:57.565 30154-30154/org.eyeseetea.malariacare.questmark_dev D/CompositeScoreDB: Executing getCompositeScoreChildren for id_composite_score: 913
07-03 07:18:57.567 30154-30154/org.eyeseetea.malariacare.questmark_dev D/CompositeScoreDB: Executing getCompositeScoreChildren for id_composite_score: 912
07-03 07:18:57.569 30154-30154/org.eyeseetea.malariacare.questmark_dev D/CompositeScoreDB: Executing getCompositeScoreChildren for id_composite_score: 911
07-03 07:18:57.571 30154-30154/org.eyeseetea.malariacare.questmark_dev D/CompositeScoreDB: Executing getCompositeScoreChildren for id_composite_score: 910

The first query listByprogram retrieve all necessary parent and children. It's not necessary more queries and all tree can be mapped to domain

**Review by xurxodev — APPROVED** [review]
thanks @manuelplazaspalacio, 
I have refactored the code because there were still problems and to not spend more time on this issue 
due to what @ifoche told us in the last meeting, problems:
- More one query executing
- Duplicate children in results
- Unreadable code

**Pull request merged**
