### PR TITLE
Feature re scheduling historic log

### LINKED ISSUE #1621: Re-scheduling historic log pop-up
New button & pop-up to show the complete history of the re-schedules for a concrete survey

### PR DESCRIPTION
**Pull request by idelcano**
Closes #1621

### CODE REVIEW

**Review by ifoche — CHANGES_REQUESTED** [review]
@idelcano I've introduced a comment in a reschedule with new lines and the pop-up doesn't show any comment at all now...can you give it a try?

**Comment by idelcano** [comment]
@ifoche i can't replicate this bug. 

Maybe after change the survey schedule date, this survey was moved to another place in the list. And maybe you clicked in a empty survey...

**Comment by ifoche** [comment]
Must be that, because I cannot replicate it either. Thanks anyway for re-testing @idelcano

**Review by ifoche — APPROVED** [review]
thanks @idelcano

**Pull request merged**
