### PR TITLE
Fixing languages issues

### LINKED ISSUE #1894: If you play a bit with the app, the translation jumps to English

### LINKED ISSUE #1898: If your system default language is not English, once you change the language you cannot come back to the system defined

### PR DESCRIPTION
**Pull request by Amejia481**
Closes #1898, closes #1894

### CODE REVIEW

**Review by xurxodev — CHANGES_REQUESTED** [review]
@Amejia481, @ifoche I have tested this solution and I have found some problems:
- If you have marked by default system defined and my device language is Spanish then locale es is selected and saved in preferences. When I change the language on my device to English, system defined is marked but with locale es. In this scenario, I think preference should refresh to locale en.
- When language array does not contain my device language and install app first time, any language is selected. I think system defined should be selected and my locale saved in preferences but show me strings in the default language (English)
device-2018-04-17-131416

**Comment by Amejia481** [comment]
Sure, I'll take a look!

**Comment by Amejia481** [comment]
Hi @xurxodev!
I updated the PR, please take a look at it!

Now when the user starts the app for the first time, system_defined is selected, stored in preferences, and the phone language will be displayed. In case that the language of the phone is not in the array English will be shown but system_defined is continued marked in settings and save in preferences.

* Example of opening the app for the first time, with phone langue Spanish ->   `system_defined` is selected, stored in preferences, the actual language of the phone is displayed.

gif_language_pr


* Example of `system_defined` selected and changing languages.
When `system_defined`is selected ->  `system_defined` is stored in preferences and the language displayed would be the actual lenguage of the phone (**The lenguage is always updated with the actual language of the phone**).

gif_language_pr


**Note:** The same behavior is already implemented on  pictureapp's pr https://github.com/EyeSeeTea/pictureapp/pull/2031

**Review by xurxodev — APPROVED** [review]
thanks @Amejia481

**Pull request merged**
