### PR TITLE
Feature merge v1.3 into eyeseetea

### LINKED ISSUE #2061: Bring last HNQIS 1.3 changes into development

### PR DESCRIPTION
**Pull request by idelcano**
### :pushpin: References
* **Issue:** close #2061
* **Related pull-requests:** 

### :tophat: What is the goal?

Merge v1.3_hnqis into development

### :memo: How is it being implemented?

After merge i open two emulators with questmark variant, one compiling this branch and other compiling development. I check the differences and recovery the development changes and fix bugs.
after that i open two emulators with hnqis variant, one compiling this branch and other compiling v1.3_hnqis. I check the differences and recovery the development changes and fix bugs.

i added the missing libraries as testCompile to make all the test work with new android studio versions.

### :boom: How can it be tested?

- [ ] **Use case 1:** Check the questmark variant against development
- [ ] **Use case 2:** Check the hnqis variant against v1.3_hnqis 

### :floppy_disk: Requires DB migration?

- [x] Nope, we can just merge this branch.
- [ ] Yes, but we need to apply it before merging this branch.
- [ ] Yes, it's already applied.

### :art: UI changes?

- [x] Nope, the UI remains as beautiful as it was before!
- [ ] Yeap, here you have some screenshots-

### CODE REVIEW

**Review by xurxodev — CHANGES_REQUESTED** [review]
@idelcano this branch changes push files and this one has changed with last uncoupled push tasks, can you merge with the branch of issue #2078 and resolve conflicts? thanks

**Comment by idelcano** [comment]
@xurxodev  i move this issue to test, but  the push of observations still failling.
 I open this issue: https://github.com/EyeSeeTea/malariapp/issues/2165

**Review by xurxodev — CHANGES_REQUESTED** [review]
@idelcano merging PR #2176 now there are mnay conflicts on this PR, can you resolve conflicts? thanks

**Review by xurxodev — APPROVED** [review]
thanks @idelcano

**Pull request merged**
