### PR TITLE
Feature add feedback imagevideo filter

### LINKED ISSUE #1623: Add checkbox & Filter on feedback to filter by questions containing video/image

### PR DESCRIPTION
**Pull request by idelcano**
Closes #1623 
@xurxodev you can test it with ifoche_test user. the first question has a image.

### CODE REVIEW

**Review by ifoche — CHANGES_REQUESTED** [review]
@idelcano did you test it with more than one video at the same time? I'm getting a consistent crash after adding a couple of videos to KE HNQIS HIV program. Can you give it a look?

**Comment by ifoche** [comment]
Just in case, [here](https://photos.app.goo.gl/9bhq2lL7MoGt9RNh2) a video of the crash, and the log would be this one:

```
10-12 14:18:48.659 21797-21797/org.eyeseetea.malariacare.hnqis_ng_bb D/.PreferencesState: reloadPreferences: scale: system | locationRequired: false | maxEvents: 30 | largeTextOption: false 
10-12 14:18:49.564 21797-21797/org.eyeseetea.malariacare.hnqis_ng_bb V/BoostFramework: mAcquireTouchFunc method = public int com.qualcomm.qti.Performance.perfLockAcquireTouch(android.view.MotionEvent,android.util.DisplayMetrics,int,int[])
10-12 14:19:30.096 21797-21937/org.eyeseetea.malariacare.hnqis_ng_bb D/.ScoreRegister:  mod ImproveModuleController idsurvey 124.0 score CompositeScoreDB{id_composite_score=616, hierarchical_code='5.7', label='Isoniazid Preventive Therapy (IPT)', uid_composite_score='RUthN89m1qf', order_pos=42, id_composite_score_parent=609}
10-12 14:19:30.661 21797-21937/org.eyeseetea.malariacare.hnqis_ng_bb D/.ScoreRegister:  mod ImproveModuleController idsurvey 124.0 score CompositeScoreDB{id_composite_score=616, hierarchical_code='5.7', label='Isoniazid Preventive Therapy (IPT)', uid_composite_score='RUthN89m1qf', order_pos=42, id_composite_score_parent=609}
10-12 14:19:30.734 21797-21937/org.eyeseetea.malariacare.hnqis_ng_bb D/.ScoreRegister:  mod ImproveModuleController idsurvey 124.0 score CompositeScoreDB{id_composite_score=616, hierarchical_code='5.7', label='Isoniazid Preventive Therapy (IPT)', uid_composite_score='RUthN89m1qf', order_pos=42, id_composite_score_parent=609}
10-12 14:19:41.419 21797-21797/org.eyeseetea.malariacare.hnqis_ng_bb E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                          at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                                          at android.os.Handler.handleCallback(Handler.java:751)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
```

**Comment by idelcano** [comment]
@ifoche I could not replicate it, but I've made some changes, can you try it again?

**Review by ifoche — APPROVED** [review]
The problem disappeared...so approving it. Thanks @idelcano

**Pull request merged**
