### PR TITLE
Cosmetics filter cosmetics

### LINKED ISSUE #1804: filter cosmetics

### PR DESCRIPTION
**Pull request by idelcano**
Closes #1804 
Review header filter (program & orgunits)

### CODE REVIEW

**Review by xurxodev — CHANGES_REQUESTED** [review]
@idelcano Please review this issue because in design the filter spinners are with a grey background and in this branch is black

**Comment by idelcano** [comment]
@xurxodev  i think the final design is in the .pdfs.
The grey background color is the color of the filters in the old versions and in the screens folder with the png images.

But in the new desing, as you can see in the  pdfs files, the filter background is black

I followed the desing of the .pdfs and ignore the png.

@ifoche can you confirm it?

**Comment by xurxodev** [comment]
@idelcano finally the filter should be in grey color, please review this branch

**Review by xurxodev — APPROVED** [review]
thanks @idelcano

**Pull request merged**
