### PR TITLE
Feature add server version

### LINKED ISSUE #2219: 1.4 invalid version recognition
HNQIS 1.4 app already recognize an invalid server version when trying to perform a login to a DHIS2 < 2.26, showing an alert saying that version is not supported. The requested feature is:
- On push, HNQIS must check before every push that server version didn't change. In case it's not, then an alert is shown recommending to upgrade the app and stops the push.

### PR DESCRIPTION
**Pull request by idelcano**
### :pushpin: References
* **Issue:** close #2219 

###   :gear: branches 
**app**: 
       Origin: feature-add_server_version Target: v1.4_hnqis
**bugshaker-android**: 
       Origin: downgrade_gradle_version 
**dhis2-light-sdk**:
       Origin: development
**EyeSeeTea-SDK**: 
       Origin: development
**SDK**: 
       Origin: feature-2.30_upgrade_gradle

### :tophat: What is the goal?

HNQIS 1.4 app already recognize an invalid server version when trying to perform a login to a DHIS2 < 2.26, showing an alert saying that version is not supported. The requested feature is:

On push, HNQIS must check before every push that server version didn't change. In case it's not, then an alert is shown recommending to upgrade the app and stops the push.

### :memo: How is it being implemented?

- Started cherry-pick the commits of v1.3 https://github.com/EyeSeeTea/malariapp/pull/2225 

- I have added ServerInfo repository policy workflow.

- I have added a preference to know if the server invalid is already detected

- I have added getServerInfoUseCase to check if the server invalid is already detected on the startup(base activity) and on the onresume(dashboardactivity).

- I have started the baseActivity's getServerInfoUseCase and dashboardActivity's getServerInfoUseCase from different instances to avoid strange errors debugging (when I reutilize the same getServerInfoUseCase sometimes the callback was overridden).

Note: I tried to move the PushUseCaseShould test to unit test, but we have some context dependencies inside of the push (F.E. checking network connection), and some problems with the old sdk libraries. I discarded this change at this moment.

### :boom: How can it be tested?
You can test the invalid server responses debugging with a breakpoint in line 129 of PushUseCase, changing the remoteServerInfo variable by new ServerInfo(31);

** Use case 1: ** - Realize login with https://data.psi-mis.org will show incompatible server error (25 is not compatible).

 ** Use case 2: ** - Realize login with https://latest.psi-mis.org You should login ok

 ** Use case 3: ** - Do a push with the app in minimized, with debug and breakpoint active. Change the remote server variable info as described in the note, reopen the app. 
The invalid server dialog will be shown, but only one time by session. 
If you minimize our app (without close), and open it again, the dialog will not be shown again.
But if you close the app, and open again, the dialog will show one time.

 ** Use case 4: ** - Do a push with the app displayed, debugging. 
Change the remote server variable info, and you will show the dialog. 
The invalid server dialog will be shown, but only one time by session. 
If you minimize our app (without close), and open it again, the dialog will not be shown again.
But if you close the app, and open again, the dialog will show one time.

** Use case 5: ** - Login with demo mode should work.
 **Use case 6:** - Run instrumental tests
 **Use case 7:** - Run unitary test

### :floppy_disk: Requires DB migration?

- [ ] Nope, we can just merge this branch.
- [ ] Yes, but we need to apply it before merging this branch.
- [x] Yes, it's already applied.

### :art: UI changes?

- [x] Nope, the UI remains as beautiful as it was before!
- [ ] Yeap, here you have some screenshots-

### CODE REVIEW

**Review by xurxodev — CHANGES_REQUESTED** [review]
@idelcano sorry but It's not working login for me, I can not realize login installing first time
- url: https://latest.psi-mis.org indeterminate progress and error in log cat
java.net.UnknownHostException: Unable to resolve host "latest.psi-mis.orgapi"
for this case if URL last character is not / we should add it 
- url: https://latest.psi-mis.org/  and  https://leap.psi-mis.org/  show unsupported server

**Comment by idelcano** [comment]
@xurxodev done. 
Work with:
url: https://latest.psi-mis.org/ 
url: https://latest.psi-mis.org
url: https://leap.psi-mis.org/
url: https://leap.psi-mis.org

incompatible server version:
url: https://data.psi-mis.org/
url: https://data.psi-mis.org
PD: I added the same solution to avoid missing or duplicate // and duplicate check quarantine API call fixed in v1.3 in the PR: https://github.com/EyeSeeTea/malariapp/pull/2231

**Review by xurxodev — CHANGES_REQUESTED** [review]
@idelcano I have tested all cases and work ok but the google play url in dialog does not appear
device-2019-01-18-091020

**Review by xurxodev — APPROVED** [review]
thanks @idelcano

**Pull request merged**
