### PR TITLE
Cosmetics questmark dialogs

### LINKED ISSUE #1811: Menu dialogs cosmetic changes

### PR DESCRIPTION
**Pull request by idelcano**
Closes #1811 
to review:
Assess menu dialog, feedback menu dialog, plan menu dialog, schedule fragment menu dialog and button dialog.

### CODE REVIEW

**Review by xurxodev — CHANGES_REQUESTED** [review]
@idelcano to merge with development exists many many conflicts that I don't know resolve, can you merge it? thanks

**Review by xurxodev — CHANGES_REQUESTED** [review]
@idelcano On this layouts there are many duplicate code:
For example CustomButtons and CustomTextView, I think that if you use styles, the code of layouts will be cleaner.

**Comment by idelcano** [comment]
@xurxodev i think is better create a new issue to clean the common styles after merge all cosmetics PR. 
for example create a new issue: "move common dialog buttons cosmetics to styles". 

It looks a easy issue to do.
The reason is i think is possible forget some new changes or make more hard the new merges.
.
what do you prefer?

**Review by xurxodev — COMMENTED** [review]
@idelcano I suppose that in the next Pull Request you should not change dialogs layouts then I think should not exist problems to merge. I think should create one style for Dialog buttons, for Dialog TextView another duplicate view. How this PR is related only to Dialogs I think that It's a very good moment to realize this change.

**Review by xurxodev — APPROVED** [review]
Thanks @idelcano, It's great the code reduction using styles. I have refactored a little using inheritance in styles to avoid duplicate code.

**Pull request merged**
