### PR TITLE
Change completeness colors cutoffs.

### LINKED ISSUE #2007: Change completeness colors cutoffs
For completeness charts ([see image](https://user-images.githubusercontent.com/12784825/41233101-044a594c-6d91-11e8-91b0-65b79a8a45b9.png)) we need the following thresholds:
- 99-100 high 
- 80-99 medium
- 0-80 low

### PR DESCRIPTION
**Pull request by manuelplazaspalacio**
Close #2007

### CODE REVIEW

**Review by xurxodev — CHANGES_REQUESTED** [review]
@manuelplazaspalacio I don´t understand your solution. According to what @idelcano has explained to me and issue description by @ifoche, inner circle and outer circle should have same thresholds.

For completeness charts (see image) we need the following thresholds:

99-100 high
80-99 medium
0-80 low 

But you only apply new thresholds to the outer circle, can you review it?

**Comment by manuelplazaspalacio** [comment]
In the title of the issue it says "Change completeness colours cutoffs." That means the outer circle. Nacho, when explained the issue to us, said that the changes are only for the outer circle.

**Comment by xurxodev** [comment]
I had a meeting with @ifoche and you did not understand it well. This issue only affects to complete percentages, these are:
- Survey creation (inner and outer circles in the toolbar)
- Survey list (two percentages in every item list)
- Survey dialog (from survey list to inner and outer circles)

Feedback percentages (scores) should not be affected by this issue.

Can you review it? thanks

**Review by xurxodev — APPROVED** [review]
thanks @manuelplazaspalacio

**Pull request merged**
