### PR TITLE
Maintenance/create login presenter with get servers invocation

### LINKED ISSUE #2386: Create login presenter and to add for the moment load servers use case invocation

### PR DESCRIPTION
**Pull request by xurxodev**
### :pushpin: References
* **Issue:** close #2386     
* **Related pull-requests:**

###   :gear: branches 
**app**: 
       Origin: /maintenance/create_login_presenter_with_get_servers_invocation Target: v1.5_hnqis
**bugshaker-android**: 
       Origin: downgrade_gradle_version  
**EyeSeeTea-SDK**: 
       Origin: development 
**SDK**: 
       Origin: feature-2.30_upgrade_gradle    

### :tophat: What is the goal?

Create login presenter and initially move GerServerUseCase execution and other url server logic from activity to presenter

### :memo: How is it being implemented?

- I have created LoginPresenter and I have moved GetServersUseCase execution from activity to the presenter
- I have moved other server url presentation logic from activity to the presenter

### :boom: How can it be tested?

**Use case 1:** - URL servers dropdown should work as on the previous PR
**Use case 2:** - Other URL server logic (showing or hiding the server URL edit text) should work

### :floppy_disk: Requires DB migration?

- [X] Nope, we can just merge this branch.
- [ ] Yes, but we need to apply it before merging this branch.
- [ ] Yes, it's already applied.

### :art: UI changes?

- [x] Nope, the UI remains as beautiful as it was before!
- [ ] Yeap, here you have some screenshots-

### CODE REVIEW

**Review by ifoche — CHANGES_REQUESTED** [review]
@xurxodev I got an exception when trying to login to https://data.psi-mis.org using the "Other" selection in the dropdown instead of directly selecting the server. The error's this one, and just in case it's relevant my phone is in French
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.eyeseetea.malariacare.hnqis_ng_dev, PID: 17547
    java.lang.RuntimeException: Unable to resume activity {org.eyeseetea.malariacare.hnqis_ng_dev/org.eyeseetea.malariacare.ProgressActivity}: org.hisp.dhis.client.sdk.core.common.network.ApiException: Failed to connect to data.psi-mis.org/52.213.164.236:443
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3598)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3638)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2879)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1602)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6543)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: org.hisp.dhis.client.sdk.core.common.network.ApiException: Failed to connect to data.psi-mis.org/52.213.164.236:443
        at org.hisp.dhis.client.sdk.android.api.network.NetworkUtils.call(NetworkUtils.java:152)
        at org.hisp.dhis.client.sdk.android.api.network.NetworkUtils.getCollection(NetworkUtils.java:114)
        at org.hisp.dhis.client.sdk.android.api.network.NetworkUtils.getCollection(NetworkUtils.java:66)
        at org.hisp.dhis.client.sdk.android.organisationunit.OrganisationUnitLevelApiClientImpl.getOrganisationUnitLevels(OrganisationUnitLevelApiClientImpl.java:76)
        at org.hisp.dhis.client.sdk.core.organisationunit.OrganisationUnitLevelControllerImpl.pull(OrganisationUnitLevelControllerImpl.java:55)
        at org.hisp.dhis.client.sdk.android.organisationunit.OrganisationUnitLevelInteractorImpl$3.call(OrganisationUnitLevelInteractorImpl.java:67)
        at org.hisp.dhis.client.sdk.android.organisationunit.OrganisationUnitLevelInteractorImpl$3.call(OrganisationUnitLevelInteractorImpl.java:64)
        at org.hisp.dhis.client.sdk.android.api.utils.DefaultOnSubscribe.call(DefaultOnSubscribe.java:39)
        at org.hisp.dhis.client.sdk.android.api.utils.DefaultOnSubscribe.call(DefaultOnSubscribe.java:34)
        at rx.Observable.unsafeSubscribe(Observable.java:10256)
        at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.net.ConnectException: Failed to connect to data.psi-mis.org/52.213.164.236:443
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
E/AndroidRuntime:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at org.hisp.dhis.client.sdk.android.api.network.NetworkModuleImpl$AuthInterceptor.intercept(NetworkModuleImpl.java:382)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:91)
        at org.hisp.dhis.client.sdk.android.api.network.NetworkUtils.call(NetworkUtils.java:149)
        	... 17 more
     Caused by: java.net.ConnectException: failed to connect to data.psi-mis.org/52.213.164.236 (port 443) from /:: (port 0) after 30000ms: connect failed: ENETUNREACH (Network is unreachable)
        at libcore.io.IoBridge.connect(IoBridge.java:138)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:356)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:357)
        at java.net.Socket.connect(Socket.java:616)
        at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:73)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245)
        	... 40 more
     Caused by: android.system.ErrnoException: connect failed: ENETUNREACH (Network is unreachable)
        at libcore.io.Linux.connect(Native Method)
        at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:126)
        at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
        at libcore.io.IoBridge.connect(IoBridge.java:130)
```

Thanks for looking into it!

**Comment by xurxodev** [comment]
@ifoche It's ready to test again

**Review by ifoche — APPROVED** [review]
thanks @xurxodev . Waiting for the solution for the empty fields problem and then we can merge

**Review by ifoche — APPROVED** [review]
thanks @xurxodev

**Pull request merged**
