### PR TITLE
Feature modal menu in every assessment

### LINKED ISSUE #1518: Move entry options to modal menu at the end of every assessment and feedback list entry
The typical 3 vertical points meaning that options can be executed on that line. On click, a modal menu appears with the actions that currently are being shown with the long press

### PR DESCRIPTION
**Pull request by idelcano**
Closes #1518

### CODE REVIEW

**Review by xurxodev — CHANGES_REQUESTED** [review]
@manuelplazaspalacio on this issue by @idelcano there are some design errors according to [mockup](http://web2.beckolsystem.com/hnqis/#/screens/d9978ee8-0c5a-4d1e-9629-9d294141c92c):
- from schedule tab, on the modal menu that appears when I click on three dots, the first button should has a text edit or add but always is add
- On modal menu from unsent tab, on top of dialog should show a chart according to mockup
- On modal menu from the improve tab, action plan button not working

**Comment by manuelplazaspalacio** [comment]
Design errors solved @xurxodev

**Review by xurxodev — CHANGES_REQUESTED** [review]
@idelcano the first requested changes were realized by @manuelplazaspalacio.
I have found a crash when from the new modal menu on improve module. When click on ActionPlan and then click on back button

**Review by xurxodev — APPROVED** [review]
thanks @idelcano and @manuelplazaspalacio

**Pull request merged**
