### PR TITLE
Feature use composite score domain entity in pull data

### LINKED ISSUE #2003: Use in SurveysDhisDataSource and Surveymapper CompositeScore domain entity and repository
- Currently in SurveysDhisDataSource and SurveyMapper is using CompositeScoreDB, It should use domain entity and repository as for question, option etc..

### PR DESCRIPTION
**Pull request by xurxodev**
### :pushpin: References
* **Issue:** close #2003 
* **Related pull-requests:**

### :tophat: What is the goal?

The goal is to use the composite domain entity in SurveyMapper to avoid a dependency from domain to the data layer. Currently, the dependency is with CompositeScoreDB.

### :memo: How is it being implemented?

Replace from CompositeScoreDB to CompositeScore and modify Repository to retrieve all CompositeScores. I have updated uni tests

### :boom: How can it be tested?

 **Use case 1:** Execute uni tests.
 **Use case 2:** Realize a pull in HNQIS and the app should work.

### :floppy_disk: Requires DB migration?

- [x] Nope, we can just merge this branch.
- [ ] Yes, but we need to apply it before merging this branch.
- [ ] Yes, it's already applied.

### :art: UI changes?

- [x] Nope, the UI remains as beautiful as it was before!
- [ ] Yeap, here you have some screenshots-

### CODE REVIEW

**Review by ifoche — APPROVED** [review]
@xurxodev tests are not working for me. Can you have a look to this? Specially SurveyMapperShould that's added here is not passing

**Review by ifoche — CHANGES_REQUESTED** [review]
actually I said "Approved" but it was a "Request changes" :)

**Comment by xurxodev** [comment]
@ifoche only for the record, seems an android studio bug executing test from project panel, executing ./gradlew data:testEyeseeteaDebugUnitTest  and ./gradlew data:testHnqisDebugUnitTest the test working like in Travis

**Review by ifoche — APPROVED** [review]
thanks @xurxodev. Great that you found a way to upgrade gradle later, because this bug is really annoying. All fine, approving.

**Pull request merged**
