### PR TITLE
Maintenance avoid create duplicate kedemo1 users during pull process

### LINKED ISSUE #2112: Avoid create duplicate KEdemo1 users during pull process

### PR DESCRIPTION
**Pull request by xurxodev**
### :pushpin: References
* **Issue:** close #2112 
* **Related pull-requests:** 

### :tophat: What is the goal?

Avoid creating duplicate kedemo1 users during the pull process.

### :memo: How is it being implemented?

When UserAccount is converted to EyeSeeTea user assign username.
When data values are converted to EyeSeeTea values and current value to convert is "_UploadedBy" (example: UzOOxp9OlSb) searchUser in database by userUid, username, and name because exists previous uploaded data values with userUid, username, and the name and assign the user to survey.

### :boom: How can it be tested?

- [ ] **Use case 1:** Realize login against https://data.psi-mis.org and verify after pull that only exists one KEdemo1 user in database

### :floppy_disk: Requires DB migration?

- [x] Nope, we can just merge this branch.
- [ ] Yes, but we need to apply it before merging this branch.
- [ ] Yes, it's already applied.

### :art: UI changes?

- [x] Nope, the UI remains as beautiful as it was before!
- [ ] Yeap, here you have some screenshots-

### CODE REVIEW

**Comment by ifoche** [comment]
changing the base to v1.3_hnqis. Merge to master seems to be a mistake, but @xurxodev let me know otherwise

**Review by ifoche — APPROVED** [review]
thanks @xurxodev

**Review by ifoche — CHANGES_REQUESTED** [review]
Oops, it looks like there's a test failing...can you have a look to it @xurxodev

**Comment by ifoche** [comment]
Looks like what's failing is not a test. It simply could not pass the travis compilation. Keeping this issue for the next maintenance release

**Comment by xurxodev** [comment]
Ok I will review it

**Comment by xurxodev** [comment]
@ifoche seems a temp error because I have restarted de build compilation on Travis and work

**Review by ifoche — APPROVED** [review]
thanks @xurxodev

**Pull request merged**
